global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['monitoring-prometheus:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['127.0.0.1:8888']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['monitoring-cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]

    static_configs:
      - targets:
          - http://nginx
          - http://nginx/monitoring/ok
          - http://auth/monitoring
          - http://user/monitoring
          - http://icons/monitoring

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: monitoring-blackbox:9115
